spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema : railway
        dialect : org.hibernate.dialect.MySQLDialect
        format_sql : true
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://monorail.proxy.rlwy.net:23916/railway?useSSL=false&serverTimeZone=UTC
    username: root
    password: MUgDBaqJwlXqTpWVskNwzMeDWvYriXOI
server:
  port: 8081