spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema : ptql
        dialect : org.hibernate.dialect.MySQLDialect
        format_sql : true
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:30232/ptql_bof
    username: root
    password: vhwWkwPLnnnULXZBgyeKatElPGGVsPYQ
server:
  port: 8081